name: filmeno
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  result_dart: ^1.1.1
  isar: ^3.1.0+1
  http: ^1.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  path_provider: ^2.1.3
  equatable: ^2.0.5
  go_router: ^13.2.5
  get_it: ^7.7.0
  intl: ^0.19.0
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:

  uses-material-design: true
